In [1]:
import os
import sys
project_root = os.path.dirname(os.path.abspath('.'))
if project_root not in sys.path:
    sys.path.insert(0, project_root)
__package__ = 'rampa'

from rampa.query.duckdb_tools import DataManager, ArcGISQuery

In [2]:
import osmnx as ox
import pandas as pd
import geopandas as gpd
from rampa.routing.route import Network
import contextily as ctx

# Layers

When a database connection is not provided, DataManager behaves like Data_Collection

In [ ]:
dmanager = DataManager(json_file=project_root +'/Users/mherrero/Documents/madrid_open_data/rampa/data/urls.json', populate=True)
dmanager.download_data()

But if we provide a database, we can populate it

In [4]:
dmanager_db = DataManager(json_file=project_root + '/rampa/data/urls.json', 
                          db_connection=project_root + '/rampa/data/prueba.db', 
                          populate=True)

INFO:rampa.query.arcgis_tools:Loading URL dictionary from JSON file: /Users/mherrero/Documents/madrid_open_data/rampa/data/urls.json
INFO:rampa.query.duckdb_tools:Creating collection of layers from URL dictionary.
  0%|          | 0/87 [00:00<?, ?it/s]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/GEOPORTAL/AREAS_ACTIVIDADES_PARA_MAYORES/MapServer/0
INFO:rampa.query.duckdb_tools:Stored layer AREAS_ACTIVIDADES_PARA_MAYORES in database with 305 records.
  1%|          | 1/87 [00:12<18:06, 12.63s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/GEOPORTAL/AREAS_ACTIVIDADES_PARA_MAYORES/MapServer/1
INFO:rampa.query.duckdb_tools:Stored layer EJERCICIOS_PARA_MAYORES in database with 200 records.
  2%|▏         | 2/87 [00:38<28:37, 20.20s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/GEOPORTAL/ASEOS_PUBLICOS/MapServer/0
INFO:rampa.query.duckdb_tools:Stored layer ASEOS_PUBLICOS in database with 118 records.
  3%|▎         | 3/87 [00:48<22:10, 15.84s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/GEOPORTAL/CUIDAR_A_QUIENES_NOS_CUIDAN/MapServer/0
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer CUIDAR_A_QUIENES_NOS_CUIDAN in database with 21 records.
  5%|▍         | 4/87 [01:00<19:42, 14.25s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/GEOPORTAL/JUNTOS_CONTRA_LA_SOLEDAD/MapServer/0
INFO:rampa.query.duckdb_tools:Stored layer JUNTOS_CONTRA_LA_SOLEDAD in database with 20 records.
  6%|▌         | 5/87 [01:07<15:42, 11.49s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/40
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer NOMBRES_DE_BARRIOS in database with 131 records.
  7%|▋         | 6/87 [01:27<19:30, 14.45s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/41
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer SECCIONES_CENSALES in database with 2462 records.
  8%|▊         | 7/87 [02:18<35:11, 26.39s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/42
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer DENSIDAD_POBLACION in database with 2450 records.
  9%|▉         | 8/87 [03:02<42:06, 31.98s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/43
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer EDAD_PROMEDIO in database with 2450 records.
 10%|█         | 9/87 [03:04<29:27, 22.66s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/44
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer PROPORCION_JUVENTUD in database with 2450 records.
 11%|█▏        | 10/87 [03:26<28:56, 22.56s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/45
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer PROPORCION_ENVEJECIMIENTO in database with 2450 records.
 13%|█▎        | 11/87 [03:39<24:43, 19.52s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/46
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer PROPORCION_SOBREENVEJECIMIENTO in database with 2450 records.
 14%|█▍        | 12/87 [03:41<17:45, 14.21s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/47
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer INDICE_ENVEJECIMIENTO in database with 2450 records.
 15%|█▍        | 13/87 [03:43<12:55, 10.47s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/48
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer INDICE_JUVENTUD in database with 2450 records.
 16%|█▌        | 14/87 [03:45<09:36,  7.89s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/49
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer INDICE_DEPENDENCIA in database with 2450 records.
 17%|█▋        | 15/87 [03:47<07:16,  6.06s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/50
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer INDICE_ESTRUCTURA_POBLACION_ACTIVA in database with 2450 records.
 18%|█▊        | 16/87 [03:48<05:40,  4.79s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/51
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer INDICE_REEMPLAZO_POBLACION_ACTIVA in database with 2450 records.
 20%|█▉        | 17/87 [03:50<04:37,  3.96s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_ESTRUCTURA_DEMOGRAFICA/MapServer/52
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer RAZON_PROGRESIVIDAD_DEMOGRAFICA in database with 2450 records.
 21%|██        | 18/87 [03:52<03:51,  3.36s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/151
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer TOTAL_AMBOS_SEXOS in database with 2450 records.
 22%|██▏       | 19/87 [05:33<36:52, 32.54s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/152
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_0_4_ANOS in database with 2450 records.
 23%|██▎       | 20/87 [06:25<42:58, 38.49s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/153
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_5_9_ANOS in database with 2450 records.
 24%|██▍       | 21/87 [06:27<30:15, 27.51s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/154
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_10_14_ANOS in database with 2450 records.
 25%|██▌       | 22/87 [07:36<43:07, 39.81s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/155
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_15_19_ANOS in database with 2450 records.
 26%|██▋       | 23/87 [07:38<30:22, 28.48s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/156
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_20_24_ANOS in database with 2450 records.
 28%|██▊       | 24/87 [07:40<21:34, 20.55s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/157
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_25_29_ANOS in database with 2450 records.
 29%|██▊       | 25/87 [07:42<15:27, 14.95s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/158
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_30_34_ANOS in database with 2450 records.
 30%|██▉       | 26/87 [07:44<11:11, 11.01s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/159
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_35_39_ANOS in database with 2450 records.
 31%|███       | 27/87 [07:46<08:17,  8.30s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/160
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_40_44_ANOS in database with 2450 records.
 32%|███▏      | 28/87 [07:47<06:14,  6.36s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/161
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_45_49_ANOS in database with 2450 records.
 33%|███▎      | 29/87 [07:49<04:50,  5.01s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/162
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_50_54_ANOS in database with 2450 records.
 34%|███▍      | 30/87 [07:51<03:51,  4.07s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/163
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_55_59_ANOS in database with 2450 records.
 36%|███▌      | 31/87 [07:53<03:11,  3.41s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/164
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_60_64_ANOS in database with 2450 records.
 37%|███▋      | 32/87 [07:55<02:46,  3.04s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/165
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_65_69_ANOS in database with 2450 records.
 38%|███▊      | 33/87 [07:57<02:23,  2.66s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/166
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_70_74_ANOS in database with 2450 records.
 39%|███▉      | 34/87 [07:59<02:05,  2.37s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/167
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_75_79_ANOS in database with 2450 records.
 40%|████      | 35/87 [08:00<01:53,  2.19s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/168
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_80_84_ANOS in database with 2450 records.
 41%|████▏     | 36/87 [08:02<01:47,  2.10s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/169
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_85_89_ANOS in database with 2450 records.
 43%|████▎     | 37/87 [08:04<01:39,  1.99s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/170
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_90_94_ANOS in database with 2450 records.
 44%|████▎     | 38/87 [08:06<01:36,  1.96s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/171
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_95_99_ANOS in database with 2450 records.
 45%|████▍     | 39/87 [08:08<01:35,  1.98s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/172
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer POBLACION_MAS_99_ANOS in database with 2450 records.
 46%|████▌     | 40/87 [08:10<01:35,  2.03s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/174
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer TOTAL_HOMBRES in database with 2450 records.
 47%|████▋     | 41/87 [08:12<01:36,  2.10s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/175
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer HOMBRES_0_4_ANOS in database with 2450 records.
 48%|████▊     | 42/87 [08:14<01:31,  2.03s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/176
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer HOMBRES_5_9_ANOS in database with 2450 records.
 49%|████▉     | 43/87 [08:16<01:30,  2.07s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/177
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer HOMBRES_10_14_ANOS in database with 2450 records.
 51%|█████     | 44/87 [08:18<01:25,  2.00s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/178
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer HOMBRES_15_19_ANOS in database with 2450 records.
 52%|█████▏    | 45/87 [08:20<01:24,  2.00s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/179
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer HOMBRES_20_24_ANOS in database with 2450 records.
 53%|█████▎    | 46/87 [08:22<01:20,  1.96s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/180
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer HOMBRES_25_29_ANOS in database with 2450 records.
 54%|█████▍    | 47/87 [08:24<01:16,  1.90s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/181
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer HOMBRES_30_34_ANOS in database with 2450 records.
 55%|█████▌    | 48/87 [08:26<01:14,  1.90s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/182
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer HOMBRES_35_39_ANOS in database with 2450 records.
 56%|█████▋    | 49/87 [08:27<01:10,  1.87s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/183
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer HOMBRES_40_44_ANOS in database with 2450 records.
 57%|█████▋    | 50/87 [08:29<01:08,  1.86s/it]INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/ESTADISTICA/INDICADORES_EDAD_POBLACION/MapServer/184
WARNING:rampa.query.arcgis_tools:No geometry column detected. Returning a regular DataFrame.
INFO:rampa.query.duckdb_tools:Stored layer HOMBRES_45_49_ANOS in database with 2450 records.

Alternatively, if the database already exist, we can just load the layers onto the manager

In [3]:
dmanager_read = DataManager(json_file=project_root + '/rampa/data/urls.json', 
                          db_connection=project_root + '/rampa/data/prueba.db', 
                          populate=False)

INFO:rampa.query.arcgis_tools:Loading URL dictionary from JSON file: /Users/mherrero/Documents/madrid_open_data/rampa/data/urls.json

By default, the data is kept in the database and brought only to memory when queried

In [4]:
print(len(dmanager_read.data))
layer = dmanager_read.get_layer_data('AREAS_ACTIVIDADES_PARA_MAYORES')
print(len(dmanager_read.data))

0

INFO:rampa.query.duckdb_tools:Loaded layer AREAS_ACTIVIDADES_PARA_MAYORES from database: 305 records

1

We can load all layers in memory by

In [5]:
dmanager_read.load_all_layers()
print(len(dmanager_read.data))

  0%|          | 0/87 [00:00<?, ?it/s]INFO:rampa.query.duckdb_tools:Loaded layer EJERCICIOS_PARA_MAYORES from database: 200 records
INFO:rampa.query.duckdb_tools:Loaded layer ASEOS_PUBLICOS from database: 118 records
INFO:rampa.query.duckdb_tools:Loaded layer CUIDAR_A_QUIENES_NOS_CUIDAN from database: 21 records
INFO:rampa.query.duckdb_tools:Loaded layer JUNTOS_CONTRA_LA_SOLEDAD from database: 20 records
INFO:rampa.query.duckdb_tools:Loaded layer NOMBRES_DE_BARRIOS from database: 131 records
INFO:rampa.query.duckdb_tools:Loaded layer SECCIONES_CENSALES from database: 2462 records
INFO:rampa.query.duckdb_tools:Loaded layer DENSIDAD_POBLACION from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer EDAD_PROMEDIO from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer PROPORCION_JUVENTUD from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer PROPORCION_ENVEJECIMIENTO from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer PROPORCION_SOBREENVEJECIMIENTO from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer INDICE_ENVEJECIMIENTO from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer INDICE_JUVENTUD from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer INDICE_DEPENDENCIA from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer INDICE_ESTRUCTURA_POBLACION_ACTIVA from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer INDICE_REEMPLAZO_POBLACION_ACTIVA from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer RAZON_PROGRESIVIDAD_DEMOGRAFICA from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer TOTAL_AMBOS_SEXOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_0_4_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_5_9_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_10_14_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_15_19_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_20_24_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_25_29_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_30_34_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_35_39_ANOS from database: 2450 records
 31%|███       | 27/87 [00:00<00:00, 269.21it/s]INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_40_44_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_45_49_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_50_54_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_55_59_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_60_64_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_65_69_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_70_74_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_75_79_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_80_84_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_85_89_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_90_94_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_95_99_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer POBLACION_MAS_99_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer TOTAL_HOMBRES from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_0_4_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_5_9_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_10_14_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_15_19_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_20_24_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_25_29_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_30_34_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_35_39_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_40_44_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_45_49_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_50_54_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_55_59_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_60_64_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_65_69_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_70_74_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_75_79_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_80_84_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_85_89_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_90_94_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_95_99_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer HOMBRES_MAS_99_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer TOTAL_MUJERES from database: 2450 records
 72%|███████▏  | 63/87 [00:00<00:00, 319.08it/s]INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_0_4_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_5_9_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_10_14_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_15_19_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_20_24_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_25_29_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_30_34_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_35_39_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_40_44_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_45_49_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_50_54_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_55_59_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_60_64_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_65_69_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_70_74_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_75_79_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_80_84_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_85_89_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_90_94_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_95_99_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer MUJERES_MAS_99_ANOS from database: 2450 records
INFO:rampa.query.duckdb_tools:Loaded layer ACCESIBILIDAD_ACERAS_2020 from database: 392 records
INFO:rampa.query.duckdb_tools:Loaded layer ACCESIBILIDAD_ACERAS_2021 from database: 202 records
INFO:rampa.query.duckdb_tools:Loaded layer ACCESIBILIDAD_ACERAS_2024 from database: 188 records
100%|██████████| 87/87 [00:00<00:00, 320.94it/s]

87

# Routing

We can start by downloading the graph defined by a boundary. The optional argument db allows us to store the graph using duckdb.

In [3]:
lay = ArcGISQuery('https://sigma.madrid.es/hosted/rest/services/CARTOGRAFIA/ANCHO_MEDIO_ACERA/MapServer/0')
lay.create_layer()
aceras = lay.query(where="1=1")
madrid = ox.geocoder.geocode_to_gdf('R5326784', by_osmid=True)
net = Network(madrid, db=project_root + '/rampa/data/grafo.db', db_alt=project_root + '/rampa/data/grafo_alt.db', aceras=aceras, row='Ancho_medio', store=True)

INFO:rampa.query.arcgis_tools:Creating FeatureLayer from URL https://sigma.madrid.es/hosted/rest/services/CARTOGRAFIA/ANCHO_MEDIO_ACERA/MapServer/0
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: sigma.madrid.es. Connection pool size: 10

Downloading network
Generating contraction hierarchies with 1 threads.
Setting CH node vector of size 165387
Setting CH edge vector of size 495988
Range graph removed 501892 edges of 991976
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%

/Users/mherrero/Documents/madrid_open_data/rampa/routing/route.py:217: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  self.edges_alt[self.row] = self.edges_alt[self.row].fillna(0)

Generating contraction hierarchies with 1 threads.
Setting CH node vector of size 165387
Setting CH edge vector of size 495988
Range graph removed 501892 edges of 991976
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
Storing network in DuckDB
Storing network in DuckDB

After it's saved into the DB, we can simply load it from there, without need to download it again

In [3]:
net_db = Network(db=project_root + '/rampa/data/grafo.db', db_alt=project_root + '/rampa/data/grafo_alt.db')

Downloading network
Generating contraction hierarchies with 1 threads.
Setting CH node vector of size 165387
Setting CH edge vector of size 495988
Range graph removed 501892 edges of 991976
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%
Generating contraction hierarchies with 1 threads.
Setting CH node vector of size 165387
Setting CH edge vector of size 495988
Range graph removed 501892 edges of 991976
. 10% . 20% . 30% . 40% . 50% . 60% . 70% . 80% . 90% . 100%

Nodes and edges are stored in their corresponding dataframes

In [4]:
net_db.nodes

                    x          y
index
171946      -3.684443  40.421247
171951      -3.688989  40.417360
171952      -3.688980  40.414991
171953      -3.688901  40.412775
20952893    -3.597241  40.430465
...               ...        ...
13069374949 -3.759205  40.401607
13069761885 -3.688659  40.477519
13069761886 -3.688402  40.477475
13069761888 -3.688615  40.477678
13069761889 -3.688359  40.477641

[165387 rows x 2 columns]

In [5]:
net_db.edges

               from           to    distance
0            171946  11218044065    3.817747
1            171946   1209330272   33.546989
2            171946   3280496563   28.937732
3            171951     26486638  125.173331
4            171951   1209331009   18.732956
...             ...          ...         ...
495983  13069761888  13069761885   18.114956
495984  13069761888  13069761889   22.058976
495985  13069761889   5676730807   70.251765
495986  13069761889  13069761888   22.058976
495987  13069761889   9619298485    4.340318

[495988 rows x 3 columns]

In [6]:
net_db.edges_alt

,from,to,distance,Ancho_medio,accesibility,alt_distance
0,171946,11218044065,3.817747,0.000000,0,3.817747
1,171946,1209330272,33.546989,4.245921,1,3.354699
2,171946,3280496563,28.937732,0.000000,0,28.937732
3,171951,26486638,125.173331,0.000000,0,125.173331
4,171951,1209331009,18.732956,0.000000,0,18.732956
...,...,...,...,...,...,...
495983,13069761888,13069761885,18.114956,0.000000,0,18.114956
495984,13069761888,13069761889,22.058976,0.000000,0,22.058976
495985,13069761889,5676730807,70.251765,0.000000,0,70.251765
495986,13069761889,13069761888,22.058976,0.000000,0,22.058976
495987,13069761889,9619298485,4.340318,0.000000,0,4.340318

The routing engine works by invoking route or route_gdf. The first returns a list of nodes, the second a gdf.

In [2]:
coord1 = (-3.703790, 40.416775)  # Example coordinates for Madrid in (longitude, latitude) format.
coord2 = (-3.72, 40.416775)

In [3]:
ruta = net_db.route_gdf(coord1, coord2, alternate=False)
ruta_alt = net_db.routÇe_gdf(coord1, coord2, alternate=True)

NameError: name 'net_db' is not defined

In [4]:
ax = ruta.plot(
    label=f"Rutas normal {ruta['distance'].sum():.0f} m",
    figsize=(10, 10)
)
ruta_alt.plot(
    ax=ax,
    color='red',
    label=f"Ruta accesible {ruta_alt['distance'].sum():.0f} m"
)

# Add legend explicitly
ax.legend()
ax.set_axis_off()

ctx.add_basemap(ax, crs=ruta.crs)

NameError: name 'ruta' is not defined

In [1]:
ruta

NameError: name 'ruta' is not defined